<?php
    // Tag the page as a sub-page, not index, for nav links
    $is_subpage = true;
    $pageTitle = 'Matthew Valdez - Trivia Game';
    $pageDescription = 'Trivia game built with Flask framework';
    $topics = [
        'Flask development',
        'deployment',
        'python',
        'frameworks',
        'learning'
    ];
    include 'header.php'; 
?>

<main class="case-study">
  <div class="case-layout">
    <article class="case-article">

      <header class="case-header">
        <h1>How I Built a Trivia Game—and the Data Behind It</h1>
        <p class="description"><?php echo $pageDescription; ?></p>
        <p class="meta categories">
          <span>Flask • </span>
          <span>Python Framework • </span>
          <span>Deployment • </span>
          <span>Entertainment</span>
        </p>

        <figure class="case-lead-img">
          <img src="/img/" alt="">
          <figcaption>caption</figcaption>
        </figure>
        <p class="byline">
          <span class="author fw-bold">Matthew Valdez</span> / 
          <time datetime="2026-02-02" class="fw-bold">Feb 2, 2026</time>
        </p>
      </header>

      <section class="case-content">

        <!-- Example with unordered list -->
        <p>This project grew out of an interest in how Jeopardy! contestants increasingly use data to guide their training—tracking performance, identifying weak areas, and focusing effort where it matters most. While building a trivia game, the real goal in my mind was creating a platform that could eventually evaluate where I was strongest, where I struggled, and how that changed over time. I love the show and still hope to be a contestant someday.</p>
        <!-- Block quote - standalone not extract remove quote -->
        <blockquote class="pull-quote">
          <!-- <i class="bi bi-quote"></i> -->
          <p>Rather than building trivia for trivia’s sake, I approached this project as a data collection and analysis problem, with gameplay as the interface.</p>
        </blockquote>
        <h2>Design Goals and Motivation</h2>
        <p>That goal shaped the project from the start. Beyond gameplay, I wanted a system that treated each interaction as data: questions answered, accuracy, categories, timing, and user context. Coming from a supply chain background, I naturally think in terms of systems—inputs, validation, flow, and measurement—and this project became a way to apply that mindset to a user-facing application.</p>
        <p>I built the application using Flask, a lightweight Python web framework that provides structure without unnecessary overhead. Using Python on the back end made it straightforward to implement game logic, validate user input, and analyze the data generated by gameplay. Flask also includes tools for managing form submissions, user sessions, and authentication, allowing me to focus on application behavior and data integrity rather than low-level plumbing.</p>
        <p>I chose to make the project web-based for accessibility and simplicity rather than developing a native app. The interface is intentionally minimal, with an emphasis on clarity and usability. For styling and responsiveness, I used Bootstrap to ensure the game works smoothly across both desktop and mobile devices.</p>
        <!-- <ul>
          <li><span class="term">Better Mental and Physical Health:</span> Access to green spaces has been linked to reduced stress, improved mood, and increased physical activity.</li>
          <li><span class="term">Increased Property Values:</span> Properties in well-treed areas often have higher market values due to the aesthetic and environmental benefits provided by the canopy.</li>
          <li><span class="term">Reduction in Crime:</span> Some studies suggest that greener neighborhoods experience lower crime rates and tend to have reduced rates of less graffiti, vandalism, and litter.</li>
        </ul>
   -->


        <!-- sub header with clickable image -->
        <!-- <h3>How the Analysis Was Done</h3>
        <figure class="case-lead-img">
          <img src="/img/canopy-dashboard.png" 
              alt="Screenshot of Tableau Dashboard"
              class="clickable-image"
              data-fullsize="/img/canopy-dashboard.png">
          <figcaption>Tree Canopy Dashboard - <a href="https://public.tableau.com/app/profile/matthew.valdez/viz/Seattle_Tree_Canopy/SeattleTreeCanopyDashboard" target="_blank">Explore the dashboard in Tableau <i class="bi bi-box-arrow-up-right"></i></a></figcaption>
        </figure> -->

        <!-- <h3>Final Thoughts</h3>
        <p>I would like to thank the City of Seattle for making a wealth of important datasets publicly available. Examining relevant, well-curated data can offer valuable insights and empower residents to take action or engage in more informed discussions about issues that impact our quality of life.</p>
        <p>Reflecting on the results, I was surprised to learn that Seattle lost approximately 250 acres of tree canopy within a five-year span, and that disparities related to race and health closely mirror national trends. Anecdotally, I experience Seattle as a leafy, green city with a progressive government that prioritizes environmental stewardship and social equity.</p>
        <p>This contrast highlights the importance of producing and analyzing data to ground decisions in evidence rather than perception. Data helps surface patterns that may not be immediately visible and allows us to identify specific areas where targeted intervention is needed.</p>
        <p>By leveraging these insights, cities like Seattle can work toward creating a healthier, more equitable urban environment for all residents.</p>
 -->


      </section>

      <!-- References - if applicable. Keep in own section.  -->
      <!-- <section aria-labelledby="references" class="case-content">
        <h2 id="references">References</h2>

        <ol class="references">
          <li id="ref-1">
            Center for Watershed Protection.
            <a href="https://cwp.org/urban-tree-canopy/" target="_blank" rel="noopener">
              Urban Tree Canopy
            </a>.
          </li>

          <li id="ref-2">
            Urban Canopy Works.
            <a href="https://www.urbancanopyworks.com/services-of-urban-trees.html" target="_blank" rel="noopener">
              Why Urban Tree Canopy Is Important for Cities
            </a>.
          </li>

          <li id="ref-3">
            City of Seattle Open Data Portal.
            <a href="https://data.seattle.gov/dataset/Existing-Tree-Canopy-/j6bn-vr2d/about_data" target="_blank" rel="noopener">
              Existing Tree Canopy (%)
            </a>.
          </li>

          <li id="ref-4">
            Policy Perspectives.
            <a href="https://policy-perspectives.org/2022/02/17/how-racism-has-shaped-the-presence-of-urban-tree-cover-in-public-spaces/" target="_blank" rel="noopener">
              How Racism Has Shaped the Presence of Urban Tree Cover in Public Spaces
            </a>.
          </li>
        </ol>
      </section> -->




    </article>

    <aside class="case-sidebar">

      <div class="sidebar-box">
        <h3>Related Case Studies</h3>
        <nav class="sidebar-links">
          <!-- <a href="trivia.php">Trivia Game With Flask</a> -->
          <a href="stocks.php">Personal Stock Screener</a>
          <a href="seattle-trees.php">Seattle Tree Canopy Visualized</a>
          <a href="db-norm.php">Database Normalization</a>
        </nav>
      </div>

      <div class="sidebar-box">
        <h3>Data & Resources</h3>
        <nav class="sidebar-links">
          <a href="https://data.seattle.gov/" target="_blank">Seattle Open Data Portal</a>
          <a href="https://data.seattle.gov/dataset/Seattle-Tree-Canopy-2016-2021-Block-Groups/az78-wea3/about_data" target="_blank">Tree Canopy Dataset</a>
          <a href="https://www.census.gov/programs-surveys/acs" target="_blank">US Census / ACS</a>
        </nav>
      </div>

    </aside>

  </div>
</main>

<!-- Script for the lightbox (image zoom) functionality -->
<script>
// Create lightbox on page load
document.addEventListener('DOMContentLoaded', function() {
  // Create lightbox HTML
  const lightbox = document.createElement('div');
  lightbox.className = 'lightbox';
  lightbox.innerHTML = `
    <button class="lightbox-close">&times;</button>
    <img src="" alt="">
  `;
  document.body.appendChild(lightbox);

  const lightboxImg = lightbox.querySelector('img');
  const closeBtn = lightbox.querySelector('.lightbox-close');

  // Add click handlers to all clickable images
  document.querySelectorAll('.clickable-image').forEach(img => {
    img.addEventListener('click', function() {
      const fullsizeSrc = this.getAttribute('data-fullsize') || this.src;
      lightboxImg.src = fullsizeSrc;
      lightboxImg.alt = this.alt;
      lightbox.classList.add('active');
    });
  });

  // Close lightbox when clicking background or close button
  lightbox.addEventListener('click', function(e) {
    if (e.target === lightbox || e.target === closeBtn) {
      lightbox.classList.remove('active');
    }
  });

  // Close with ESC key
  document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape' && lightbox.classList.contains('active')) {
      lightbox.classList.remove('active');
    }
  });
});
</script>

<?php include 'footer.php'; ?>